name: "change-data-capture"
services:

  kafka-broker:
    image: apache/kafka:4.0.1-rc0
    container_name: kafka-broker
    hostname: kafka-broker
    working_dir: /opt/kafka/bin
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LOG_DIR=/tmp/kafka-logs
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PYTHONCLIENT://:29092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092,PYTHONCLIENT://localhost:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PYTHONCLIENT:PLAINTEXT
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      # - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      # - KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS=
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.3.0
    ports:
      - 8080:8080
    depends_on:
      - kafka-broker
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - DYNAMIC_CONFIG_PATH=/etc/kafkaui/dynamic_config.yaml
      - CONFIG_RELATED_UPLOADS_DIR=/etc/kafkaui/uploads
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
      - ./kui/uploads:/etc/kafkaui/uploads

  postgres:
    image: postgres:14
    hostname: postgres
    environment:
      - POSTGRES_USER=change_data_capture
      - POSTGRES_PASSWORD=change_data_capture
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka-connect:
    hostname: kafka-connect
    image: quay.io/debezium/connect:2.7.4.Final
    ports:
      - "8083:8083"
    # https://kafka.apache.org/documentation/#connectconfigs
    # https://docs.confluent.io/platform/7.3/installation/docker/config-reference.html#kconnect-long-configuration
    environment:
      BOOTSTRAP_SERVERS: "kafka-broker:9092"
      GROUP_ID: "connect-source-cluster"
      REST_PORT: "8083"
      CONFIG_STORAGE_TOPIC: "_connect-configs"
      OFFSET_STORAGE_TOPIC: "_connect-offsets"
      STATUS_STORAGE_TOPIC: "_connect-status"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      REST_ADVERTISED_HOST_NAME: "kafka-connect-source"
      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"
      PLUGIN_DISCOVERY: "HYBRID_FAIL"
      # PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/usr/share/confluent-hub-components/debezium-debezium-connector-postgresql/lib"
    depends_on:
      - kafka-broker
    volumes:
      - ./connect/plugins:/kafka/connect/plugins

  create-kafka-connectors:
    image: curlimages/curl:8.16.0
    command: [ "sh", "/home/curl_user/kafka-connect/create-connectors.sh", "/home/curl_user/kafka-connectors" ]
    volumes:
      - ./connect:/home/curl_user/kafka-connect
      - ./connectors:/home/curl_user/kafka-connectors
    depends_on:
      - kafka-broker
      - kafka-connect
      - kafbat-ui

volumes:
  pgdata:
