name: "change-data-capture"
services:

  kafka-broker:
    image: apache/kafka:4.0.1-rc0
    container_name: kafka-broker
    hostname: kafka-broker
    working_dir: /opt/kafka/bin
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LOG_DIR=/tmp/kafka-logs
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      # - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      # - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      # - KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS=
    ports:
      - 9092:9092
      - 9093:9093

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.3.0
    ports:
      - 8080:8080
    depends_on:
      - kafka-broker
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - DYNAMIC_CONFIG_PATH=/etc/kafkaui/dynamic_config.yaml
      - CONFIG_RELATED_UPLOADS_DIR=/etc/kafkaui/uploads
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
      - ./kui/uploads:/etc/kafkaui/uploads
